export const TableData = [
  {
    name: "Halo Branded Solutions Inc",
    value: "$45,543,404",
  },
  {
    name: "HUB Folding Box Inc",
    value: "$5,673,154",
  },
  {
    name: "Motive Marketing Group",
    value: "$4,395,403",
  },
  {
    name: "Ben S. Loeb LLC",
    value: "$2,764,325",
  },
  {
    name: "Signature Marketing Inc",
    value: "$1,470,806",
  },
  {
    name: "Beverage Merchandising",
    value: "$1,407,559",
  },
  {
    name: "Havoc Live LLC",
    value: "$1,265,878",
  },
  {
    name: "AJ Displays Inc",
    value: "$1,158,586",
  },
  {
    name: "Lone Star Corrugated Container",
    value: "$1,133,349",
  },
  {
    name: "Primary Color Systems",
    value: "$1,075,946",
  },
  {
    name: "Halo Branded Solutions Inc",
    value: "$45,543,404",
  },
  {
    name: "HUB Folding Box Inc",
    value: "$5,673,154",
  },
  {
    name: "Motive Marketing Group",
    value: "$4,395,403",
  },
  {
    name: "Ben S. Loeb LLC",
    value: "$2,764,325",
  },
  {
    name: "Signature Marketing Inc",
    value: "$1,470,806",
  },
  {
    name: "Beverage Merchandising",
    value: "$1,407,559",
  },
  {
    name: "Havoc Live LLC",
    value: "$1,265,878",
  },
  {
    name: "AJ Displays Inc",
    value: "$1,158,586",
  },
  {
    name: "Lone Star Corrugated Container",
    value: "$1,133,349",
  },
  {
    name: "Primary Color Systems",
    value: "$1,075,946",
  },
];

export const TableProjectData = [
  {
    name: "Super Bowl 2025",
    status: "RFx Issued",
    category: "POS Drinkwear",
    date: "4/23/25",
  },
  {
    name: "Back To School",
    status: "Awaiting Responses",
    category: "POS Displosable Display",
    date: "8/5/25",
  },
  {
    name: "Código Walgreens",
    status: "Responses Received",
    category: "POS Permanent Display",
    date: "6/3/26",
  },
  {
    name: "Jameson Aldi",
    status: "Under Evaluation",
    category: "POS Gifts",
    date: "5/4/25",
  },
  {
    name: "Jameson St. Patty’s Day",
    status: "Completed",
    category: "POS Serving Material",
    date: "3/2/25",
  },
  {
    name: "Absolut March Madness",
    status: "Cancelled",
    category: "POS Gifts",
    date: "1/6/25",
  },
  {
    name: "Malibu Spring Break",
    status: "Completed",
    category: "POS Gifts",
    date: "5/20/25",
  },
  {
    name: "Super Bowl 2025",
    status: "RFx Issued",
    category: "POS Drinkwear",
    date: "4/23/25",
  },
  {
    name: "Back To School",
    status: "Awaiting Responses",
    category: "POS Displosable Display",
    date: "8/5/25",
  },
  {
    name: "Código Walgreens",
    status: "Responses Received",
    category: "POS Permanent Display",
    date: "6/3/26",
  },
  {
    name: "Jameson Aldi",
    status: "Under Evaluation",
    category: "POS Gifts",
    date: "5/4/25",
  },
];
export const TableSupplierData = [
  {
    name: "Halo Branded Solutions Inc",
    category: "POS Gifts, POS Perm. Visibility",
    status: "Active",
    location: "USA",
    payment: "Net 60",
  },
  {
    name: "HUB Folding Box Inc",
    category: "Permanent Visibility Disposable Display",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Motive Marketing Group",
    category: "Serving Material Gifts Permanent Displays",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Ben S. Loeb LLC",
    category: "Drinkwear",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Signature Marketing Inc",
    category: "Garments and Accessories",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Beverage Merchandising",
    category: "Garments and Accessories",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Havoc Live LLC",
    category: "Permanent Visibility Disposable Display",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Halo Branded Solutions Inc",
    category: "POS Gifts, POS Perm. Visibility",
    status: "Active",
    location: "USA",
    payment: "Net 60",
  },
  {
    name: "HUB Folding Box Inc",
    category: "Permanent Visibility Disposable Display",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Motive Marketing Group",
    category: "Serving Material Gifts Permanent Displays",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
  {
    name: "Ben S. Loeb LLC",
    category: "Drinkwear",
    status: "Active",
    location: "USA",
    payment: "Net 90",
  },
];

export const TableSupplierDetailData = [
  {
    name: "Ben S. Loeb LLC",
    value: "$20,000,0",
    status: "Expired",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "30%",
    contact: "ben@gmail.com",
  },
  {
    name: "Halo Branded Solutions Inc",
    value: "$300,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "40%",
    contact: "halo@gmail.com",
  },
  {
    name: "HUB Folding Box Inc",
    value: "$70,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "70%",
    contact: "Folding@gmail.com",
  },
  {
    name: "Ben S. Loeb LLC",
    value: "$20,000,0",
    status: "Expired",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "30%",
    contact: "ben@gmail.com",
  },
  {
    name: "Halo Branded Solutions Inc",
    value: "$300,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "40%",
    contact: "halo@gmail.com",
  },
  {
    name: "HUB Folding Box Inc",
    value: "$70,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "70%",
    contact: "Folding@gmail.com",
  },
  {
    name: "Ben S. Loeb LLC",
    value: "$20,000,0",
    status: "Expired",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "30%",
    contact: "ben@gmail.com",
  },
  {
    name: "Halo Branded Solutions Inc",
    value: "$300,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "40%",
    contact: "halo@gmail.com",
  },
  {
    name: "HUB Folding Box Inc",
    value: "$70,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "70%",
    contact: "Folding@gmail.com",
  },
  {
    name: "Ben S. Loeb LLC",
    value: "$20,000,0",
    status: "Expired",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "30%",
    contact: "ben@gmail.com",
  },
  {
    name: "Halo Branded Solutions Inc",
    value: "$300,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "40%",
    contact: "halo@gmail.com",
  },
  {
    name: "HUB Folding Box Inc",
    value: "$70,000,0",
    status: "Active",
    expire_date: "01/01/25",
    effective_date: "01/01/25",
    payment_term: 60,
    rebate: "Y",
    savings: "70%",
    contact: "Folding@gmail.com",
  },
];
